"""Initial migration.

Revision ID: 09cabcbbe9be
Revises: 
Create Date: 2024-08-10 23:29:44.906893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cabcbbe9be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('mail', sa.String(), nullable=False),
    sa.Column('phoneNumber', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DeviceType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviceType', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CustomerDevice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('deviceTypeId', sa.Integer(), nullable=False),
    sa.Column('port', sa.String(), nullable=False),
    sa.Column('ipHost', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['Customer.id'], ),
    sa.ForeignKeyConstraint(['deviceTypeId'], ['DeviceType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CustomerDevice')
    op.drop_table('DeviceType')
    op.drop_table('Customer')
    # ### end Alembic commands ###
